apiVersion: v1
kind: Pod
metadata:
  name: roadsterpod
  labels:
    appName: roadster
    version: "1"
    env: stage
spec:
  containers:
    - name: roadster
      image: techsriman/roadster:1.0
      ports:
        - name: tomcatport
          containerPort: 8080
          protocol: TCP    