apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginxdaemonset
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx    
    